// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Webtor Support",
            "url": "https://webtor.io/support",
            "email": "support@webtor.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/resource/": {
            "post": {
                "description": "Receives torrent or magnet-uri in request body.\nIf magnet-uri provided instead of torrent, then it tries to fetch torrent from BitTorrent network (timeout 3 minutes).",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "Stores resource",
                "parameters": [
                    {
                        "example": "\"magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10\u0026dn=Sintel\u0026tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969\u0026tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969\u0026tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337\u0026tr=udp%3A%2F%2Fexplodie.org%3A6969\u0026tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337\u0026tr=wss%3A%2F%2Ftracker.btorrent.xyz\u0026tr=wss%3A%2F%2Ftracker.openwebtorrent.com\u0026tr=wss%3A%2F%2Ftracker.fastcast.nz\u0026ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F\"",
                        "description": "resource",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ResourceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resource/{resource_id}": {
            "get": {
                "description": "Receives resource id and returns resource.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "Returns resource",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"08ada5a7a6183aae1e09d831df6748d566095a10\"",
                        "description": "resource_id",
                        "name": "resource_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ResourceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resource/{resource_id}.torrent": {
            "get": {
                "description": "Receives id and returns torrent file (binary, Content-Type application/x-bittorrent) for resource.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/x-bittorrent"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "Returns torrent for resource",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"08ada5a7a6183aae1e09d831df6748d566095a10\"",
                        "description": "resource_id",
                        "name": "resource_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "torrent file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resource/{resource_id}/export/{content_id}": {
            "get": {
                "description": "Provides url for exporting resource content. content_id is\neither the SHA1 of the file's path (returned by /list) or\nthe file's index in the torrent's natural file order\n(matches the fileIdx convention used by Stremio addons).",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Exports resource content",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"08ada5a7a6183aae1e09d831df6748d566095a10\"",
                        "description": "resource_id",
                        "name": "resource_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"ca2453df3e7691c28934eebed5a253ee0aabd29f\"",
                        "description": "content_id",
                        "name": "content_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"download,stream\"",
                        "description": "comma-separated list of export types to generate; allowed values: download, stream, torrent_client_stat, subtitles, media_probe; if omitted or empty, all types are exported; an unknown value yields 400",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "API key embedded into the generated export URLs; falls back to X-Api-Key header, then to the server-configured key",
                        "name": "api-key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "API key embedded into the generated export URLs (used if api-key query parameter is absent)",
                        "name": "X-Api-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "JWT embedded into the generated export URLs; falls back to X-Token header; if neither is provided, the server signs its own token with the configured role; the token's role claim selects the premium domain and download subdomains",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "JWT embedded into the generated export URLs (used if token query parameter is absent)",
                        "name": "X-Token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "opaque user identifier propagated into the generated export URLs; falls back to X-User-Id header",
                        "name": "user-id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "opaque user identifier propagated into the generated export URLs (used if user-id query parameter is absent)",
                        "name": "X-User-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "request correlation identifier propagated into the generated export URLs; falls back to X-Request-Id header",
                        "name": "request-id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "request correlation identifier propagated into the generated export URLs (used if request-id query parameter is absent)",
                        "name": "X-Request-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "true",
                        "description": "any value except \\",
                        "name": "use-premium-domain",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IMDB identifier forwarded into the subtitles export URL (subtitles type only)",
                        "name": "imdb-id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "zip",
                            "tar"
                        ],
                        "type": "string",
                        "default": "zip",
                        "description": "archive format for directory downloads",
                        "name": "archive-format",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "limit a directory archive to the selected file/folder paths (repeatable); each path must exist in the torrent and be inside the exported directory; at most 1024 paths and about 6000 percent-encoded bytes in total",
                        "name": "paths",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ExportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resource/{resource_id}/list": {
            "get": {
                "description": "Lists files and directories of specific resource.\nAll ids in response can be used for export.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list"
                ],
                "summary": "Lists resource",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"08ada5a7a6183aae1e09d831df6748d566095a10\"",
                        "description": "resource_id",
                        "name": "resource_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "path",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "list",
                            "tree"
                        ],
                        "type": "string",
                        "description": "output",
                        "name": "output",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name",
                            "size"
                        ],
                        "type": "string",
                        "description": "sort order; if omitted, items are returned in the torrent's original file order",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/speedtest": {
            "get": {
                "description": "Returns urls for measuring download speed. Each url points to a /speedtest endpoint on a download host and carries the size, token and api-key query parameters.\nThe \"standard\" url is always present; a \"premium\" url is added when a premium domain is configured. The token's role claim selects which download subdomains are eligible.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "speedtest"
                ],
                "summary": "Returns speed test urls",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT embedded into the generated speed test URLs; falls back to X-Token header; if neither is provided, the server signs its own token with the configured role",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "JWT embedded into the generated speed test URLs (used if token query parameter is absent)",
                        "name": "X-Token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "API key embedded into the generated speed test URLs; falls back to X-Api-Key header, then to the server-configured key",
                        "name": "api-key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "API key embedded into the generated speed test URLs (used if api-key query parameter is absent)",
                        "name": "X-Api-Key",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.SpeedtestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "services.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "services.ExportItem": {
            "type": "object",
            "properties": {
                "html_tag": {
                    "$ref": "#/definitions/services.ExportTag"
                },
                "meta": {
                    "$ref": "#/definitions/services.ExportMeta"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "services.ExportKindType": {
            "type": "string",
            "enum": [
                "subtitles"
            ],
            "x-enum-varnames": [
                "ExportKindTypeSubtitles"
            ]
        },
        "services.ExportMeta": {
            "type": "object",
            "properties": {
                "cache": {
                    "type": "boolean"
                },
                "multibitrate": {
                    "type": "boolean"
                },
                "transcode": {
                    "type": "boolean"
                },
                "transcode_cache": {
                    "type": "boolean"
                }
            }
        },
        "services.ExportPreloadType": {
            "type": "string",
            "enum": [
                "auto",
                "none"
            ],
            "x-enum-varnames": [
                "ExportPreloadTypeAuto",
                "ExportPreloadTypeNone"
            ]
        },
        "services.ExportResponse": {
            "type": "object",
            "properties": {
                "exports": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/services.ExportItem"
                    }
                },
                "source": {
                    "$ref": "#/definitions/services.ListItem"
                }
            }
        },
        "services.ExportSource": {
            "type": "object",
            "properties": {
                "src": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "services.ExportTag": {
            "type": "object",
            "properties": {
                "alt": {
                    "type": "string"
                },
                "poster": {
                    "type": "string"
                },
                "preload": {
                    "$ref": "#/definitions/services.ExportPreloadType"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.ExportSource"
                    }
                },
                "src": {
                    "type": "string"
                },
                "tag": {
                    "$ref": "#/definitions/services.ExportTagName"
                },
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.ExportTrack"
                    }
                }
            }
        },
        "services.ExportTagName": {
            "type": "string",
            "enum": [
                "video",
                "audio",
                "img"
            ],
            "x-enum-varnames": [
                "ExportTagNameVideo",
                "ExportTagNameAudio",
                "ExportTagNameImage"
            ]
        },
        "services.ExportTrack": {
            "type": "object",
            "properties": {
                "kind": {
                    "$ref": "#/definitions/services.ExportKindType"
                },
                "label": {
                    "type": "string"
                },
                "src": {
                    "type": "string"
                },
                "srclang": {
                    "type": "string"
                }
            }
        },
        "services.ListItem": {
            "type": "object",
            "properties": {
                "ext": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "index": {
                    "description": "Index is the file's position in the torrent's natural file order\n(r.Files), i.e. the content_id accepted by /resource/\u003chash\u003e/export/\u003cidx\u003e.\nValid only for Type == file items; directory items leave it zero. Lets\nclients address the file directly without re-deriving the index from\nthe sorted/paginated list order.",
                    "type": "integer"
                },
                "media_format": {
                    "$ref": "#/definitions/services.MediaFormat"
                },
                "mime_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/services.ListType"
                }
            }
        },
        "services.ListResponse": {
            "type": "object",
            "properties": {
                "ext": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "index": {
                    "description": "Index is the file's position in the torrent's natural file order\n(r.Files), i.e. the content_id accepted by /resource/\u003chash\u003e/export/\u003cidx\u003e.\nValid only for Type == file items; directory items leave it zero. Lets\nclients address the file directly without re-deriving the index from\nthe sorted/paginated list order.",
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.ListItem"
                    }
                },
                "items_count": {
                    "type": "integer"
                },
                "media_format": {
                    "$ref": "#/definitions/services.MediaFormat"
                },
                "mime_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/services.ListType"
                }
            }
        },
        "services.ListType": {
            "type": "string",
            "enum": [
                "file",
                "directory"
            ],
            "x-enum-varnames": [
                "ListTypeFile",
                "ListTypeDirectory"
            ]
        },
        "services.MediaFormat": {
            "type": "string",
            "enum": [
                "audio",
                "video",
                "image",
                "subtitle",
                "unknown"
            ],
            "x-enum-varnames": [
                "Audio",
                "Video",
                "Image",
                "Subtitle",
                "Unknown"
            ]
        },
        "services.ResourceResponse": {
            "type": "object",
            "properties": {
                "file": {
                    "description": "File is the single file of a single-file torrent (nil when MultiFile).\nLets clients skip /list for the common single-file case.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/services.ListItem"
                        }
                    ]
                },
                "files_count": {
                    "description": "FilesCount is the number of files in the torrent.",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "magnet_uri": {
                    "type": "string"
                },
                "multi_file": {
                    "description": "MultiFile is false for single-file-mode torrents (one file sitting at\nthe torrent root). Clients can render such a torrent straight away\nwithout a /list round-trip.",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "description": "Size is the torrent's total size in bytes (sum of all files). Lets\nclients read the size without paginating /list — a real win on torrents\nwith tens of thousands of files.",
                    "type": "integer"
                }
            }
        },
        "services.SpeedtestResponse": {
            "type": "object",
            "properties": {
                "urls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.SpeedtestURL"
                    }
                }
            }
        },
        "services.SpeedtestURL": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyHeader": {
            "description": "Optional API key. It is not validated by this API itself, it is embedded as api-key into the signed export/speedtest URLs and validated by the upstream services that serve them.",
            "type": "apiKey",
            "name": "X-Api-Key",
            "in": "header"
        },
        "ApiKeyQuery": {
            "description": "Optional API key passed as a query parameter. Same semantics as X-Api-Key header (query value takes precedence).",
            "type": "apiKey",
            "name": "api-key",
            "in": "query"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Webtor API",
	Description:      "Simple API to communicate with Webtor service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
